### ISSUE TITLE
RatCVS

### ISSUE THREAD

**Issue by M527-C** [johndempster/RatCVS#1]
I want download ratcvs on Mac but I don't know how ? if anyone help me to do that ,  thank you

**Comment by johndempster** [comment]
Only Windows versions of RatCVS are available for download at the moment. You can run the Windows version of RatCVS on a Mac by using  the Parallels Desktop (with a Windows O/S installed).

**Comment by M527-C** [comment]
Okay but What is VM and you can tell developer to make it for mac , thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
