### ISSUE TITLE
drugs of the unknown 

### ISSUE THREAD

**Issue by Kwabena34** [johndempster/RatCVS#2]
how do we get the answers to the unknown drugs please?

**Comment by johndempster** [comment]
The unknown drugs are

Drug A = Acetylcholine
Drug B = Adenosine
Drug C = Isoprenaline
Drug D = Noradrenaline
Drug E = Sodium nitroprusside
Drug F = Cromokalim
Drug G = Milrinone
Drug H = Propranalol
Drug I = Verapamil
Drug J = L-NOARG
Drug K = Atropine

Best Wishes

John Dempster

Strathclyde Institute for Pharmacy & Biomedical Sciences,
161 Cathedral St.
Glasgow, G4 0RE
Mob. 07970 369670

The University of Strathclyde is a charitable body, registered in Scotland, with registration number SC015263

________________________________
From: Kwabena34 ***@***.***>
Sent: 19 February 2022 22:37
To: johndempster/RatCVS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [johndempster/RatCVS] drugs of the unknown (Issue #2)

CAUTION: This email originated outside the University. Check before clicking links or attachments.

how do we get the answers to the unknown drugs please?

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohndempster%2FRatCVS%2Fissues%2F2&data=04%7C01%7Cj.dempster%40strath.ac.uk%7Cd4cdca4492bb43099b3108d9f3f8718c%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637809070665097454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0hSsoiwPboPEZsdwlzQoeK1a3mlt9Q2bYuOA7tuHmjI%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAXULOREUJMV7GUKHKI5WQTU4ALTLANCNFSM5O3RJ23Q&data=04%7C01%7Cj.dempster%40strath.ac.uk%7Cd4cdca4492bb43099b3108d9f3f8718c%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637809070665097454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iY77WaIt%2FlTmgUFV%2BJKZrQVZaExVA1%2FO%2BdU%2BVC8%2Fq1g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cj.dempster%40strath.ac.uk%7Cd4cdca4492bb43099b3108d9f3f8718c%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637809070665097454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fishnyKZHJ2xUp69GoKNx4cy20zcUaEOKbe0h31tCWs%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cj.dempster%40strath.ac.uk%7Cd4cdca4492bb43099b3108d9f3f8718c%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637809070665097454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Bqv4%2F1NE5D7n6hSKfrJMR5IQ5xHAgxSo3grkC8a%2F2yE%3D&reserved=0>.
